run:
  # default concurrency is a available CPU number
  concurrency: 4
  go: "1.22"
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  tests: true

linters:
  disable:
    - execinquery
    - exportloopref
    - gci
    - gomnd
    - testpackage
    - paralleltest

linters-settings:
  errcheck:
    exclude-functions:
    - (github.com/go-kit/kit/log.Logger).Log
  lll:
    line-length: 140
  funlen:
    lines: 110
    statements: 60
  gofumpt:
    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules: true
